//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PassWord { get; set; }
        public string Email { get; set; }
        public string CustomerTel { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> CustomerIdentity { get; set; }
        public string AlipayAccount { get; set; }
        public string Avatar { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
