//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EconomicalleagueContainer : DbContext
    {
        public EconomicalleagueContainer()
            : base("name=EconomicalleagueContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerInfo> CustomerInfo { get; set; }
        public virtual DbSet<Log_ExceptionLog> Log_ExceptionLog { get; set; }
        public virtual DbSet<Log_LoginLog> Log_LoginLog { get; set; }
        public virtual DbSet<PlatformCommission> PlatformCommission { get; set; }
        public virtual DbSet<Sys_UserInfo> Sys_UserInfo { get; set; }
        public virtual DbSet<CustomerRelatedInfo> CustomerRelatedInfo { get; set; }
        public virtual DbSet<PlatformOrders> PlatformOrders { get; set; }
        public virtual DbSet<TBItemsList> TBItemsList { get; set; }
        public virtual DbSet<UserRelation> UserRelation { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserManager> UserManager { get; set; }
        public virtual DbSet<TBrebateOrders> TBrebateOrders { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<UatmFavoritItems> UatmFavoritItems { get; set; }
    }
}
