//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformCommission
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<long> trade_parent_id { get; set; }
        public Nullable<long> trade_id { get; set; }
        public string WeChatAccount { get; set; }
        public Nullable<double> commission { get; set; }
        public Nullable<double> InDirectcommission { get; set; }
        public Nullable<double> Teamcommission { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTimed { get; set; }
    }
}
