//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformOrders
    {
        public long trade_parent_id { get; set; }
        public long trade_id { get; set; }
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string unid { get; set; }
    }
}
