//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBrebateOrders
    {
        public long TradeId { get; set; }
        public long NumIid { get; set; }
        public string ItemText { get; set; }
        public long ItemNum { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PayPrice { get; set; }
        public string SellerNick { get; set; }
        public string SellerShopTitle { get; set; }
        public string TkStatus { get; set; }
        public string IncomeRate { get; set; }
        public string Proportions { get; set; }
        public string OrderType { get; set; }
        public Nullable<double> PubSharePreFee { get; set; }
        public Nullable<double> StatementPrice { get; set; }
        public Nullable<double> PrePay { get; set; }
        public double Commission { get; set; }
        public string CommissionRate { get; set; }
        public string SubsidyRate { get; set; }
        public Nullable<double> SubsidyFee { get; set; }
        public string SubsidyType { get; set; }
        public string TerminalType { get; set; }
        public string Tk3rdType { get; set; }
        public string Category { get; set; }
        public Nullable<long> Tk3rdPubId { get; set; }
        public string Tk3rdPubName { get; set; }
        public Nullable<long> AdzoneId { get; set; }
        public string AdzoneName { get; set; }
        public Nullable<System.DateTime> ClickTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EarningTime { get; set; }
    }
}
