//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Economicalleague.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UatmFavoritItems
    {
        public long NumIid { get; set; }
        public Nullable<long> Typeid { get; set; }
        public string Title { get; set; }
        public string PictUrl { get; set; }
        public string SmallImages { get; set; }
        public Nullable<double> ReservePrice { get; set; }
        public Nullable<double> ZkFinalPrice { get; set; }
        public Nullable<long> UserType { get; set; }
        public string Provcity { get; set; }
        public string ItemUrl { get; set; }
        public string ClickUrl { get; set; }
        public string Nick { get; set; }
        public Nullable<long> SellerId { get; set; }
        public Nullable<long> Volume { get; set; }
        public Nullable<double> TkRate { get; set; }
        public Nullable<double> ZkFinalPriceWap { get; set; }
        public Nullable<long> Category { get; set; }
        public string CouponClickUrl { get; set; }
        public Nullable<System.DateTime> CouponEndTime { get; set; }
        public string CouponInfo { get; set; }
        public Nullable<System.DateTime> CouponStartTime { get; set; }
        public Nullable<long> CouponTotalCount { get; set; }
        public Nullable<long> CouponRemainCount { get; set; }
        public string CommissionRate { get; set; }
        public string EventEndTime { get; set; }
        public string EventStartTime { get; set; }
        public string ShopTitle { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> Type { get; set; }
        public string FavoritesTitle { get; set; }
        public Nullable<long> FavoritesId { get; set; }
        public int isSale { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
